const itemTagSynonyms = {
  tag: {
    "scribbled": "handwritten",
    "written by hand": "handwritten",
    "printed": "printed",
    "printout": "printed",
    "photocopied": "printed",
    "typed out": "typed",
    "typed up": "typed",
    "typed on": "typed",
    "digital display": "digital",
    "digital text": "digital",
    "on-screen": "digital",
    "pixelated": "glitching",
    "corrupted": "glitching",
    "scrambled": "glitching",
    "glitchy": "glitching",
    "weathered": "faded",
    "worn": "faded",
    "bleached": "faded",
    "weather-beaten": "faded",
    "blurred": "smudged",
    "smeared": "smudged",
    "stained": "smudged",
    "smear": "smudged",
    "ripped": "torn",
    "shredded": "torn",
    "torn up": "torn",
    "coded": "encrypted",
    "ciphered": "encrypted",
    "encoded": "encrypted",
    "cipher text": "encrypted",
    "encoded message": "encrypted",
    "secret language": "foreign",
    "alien language": "foreign",
    "unknown language": "foreign",
    "ancient script": "gothic",
    "gothic script": "gothic",
    "blackletter": "gothic",
    "medieval script": "gothic",
    "runes": "runic",
    "futhark": "runic",
    "rune-inscribed": "runic",
    "rune scribed": "runic",
    "blood stained": "bloodstained",
    "blood soaked": "bloodstained",
    "bloodied": "bloodstained",
    "water damaged": "water-damaged",
    "waterlogged": "water-damaged",
    "soaked": "water-damaged"
  }
};

export default itemTagSynonyms;
