const itemTypeSynonyms = {
  "type": {
    "single use": "single-use",
    "single-use item": "single-use",
    "one use": "single-use",
    "multi use": "multi-use",
    "multi-use item": "multi-use",
    "gear": "equipment",
    "armour": "equipment",
    "armor": "equipment",
    "tool": "equipment",
    "ammo": "ammunition",
    "ammunition": "ammunition",
    "projectiles": "ammunition",
    "affliction": "status effect",
    "hungry": "status effect",
    "thirsty": "status effect",
    "tired": "status effect",
    "sleepy": "status effect",
    "wounded": "status effect",
    "poisoned": "status effect",
    "note": "page",
    "scrap of paper": "page",
    "sheet": "page",
    "page": "page",
    "tome": "book",
    "volume": "book",
    "journal": "book",
    "diary": "book",
    "logbook": "book",
    "notebook": "book",
    "journal book": "book",
    "field journal": "book",
    "log book": "book",
    "captain's log": "book",
    "daily log": "book",
    "personal log": "book",
    "research journal": "book",
    "travelogue": "book",
    "ledger": "book",
    "book": "book",
    "fixture": "immovable",
    "built in": "immovable",
    "built-in": "immovable",
    "stationary": "immovable",
    "immovable object": "immovable",
    "picture": "picture",
    "photograph": "picture",
    "drawing": "picture",
    "chart": "map",
    "guide": "map",
    "schematic": "map",
    "road map": "map"
  }
};

export default itemTypeSynonyms;
