const mapNodeSynonyms = {
  "status": {
    "unknown": "undiscovered",
    "default": "undiscovered",
    "unrevealed": "undiscovered",
    "normal": "undiscovered",
    "not found": "undiscovered",
    "not discovered": "undiscovered",
    "unexplored": "undiscovered",
    "unexplored area": "undiscovered",
    "unexplored region": "undiscovered",
    "unexplored zone": "undiscovered",
    "unexplored territory": "undiscovered",
    "not explored": "undiscovered",
    "found": "discovered",
    "opened": "discovered",
    "known": "discovered",
    "open": "discovered",
    "accessible": "discovered",
    "visited": "discovered",
    "explored": "discovered",
    "available": "discovered",
    "functional": "discovered",
    "usable": "discovered",
    "revealed": "discovered",
    "active": "discovered",
    "rumoured": "rumored",
    "speculation": "rumored",
    "whispered": "rumored",
    "legendary": "rumored",
    "hidden": "rumored",
    "concealed": "rumored",
    "goal": "quest_target",
    "objective": "quest_target",
    "inaccessible": "blocked",
    "sealed off": "blocked",
    "sealed shut": "blocked",
    "sealed tight": "blocked",
    "sealed": "blocked",
    "broken": "blocked",
    "cut off": "blocked",
    "defeated": "blocked",
    "ruined": "blocked",
    "damaged": "blocked",
    "collapsed": "blocked",
    "blocked off": "blocked",
    "barricaded": "blocked",
    "barred": "blocked",
    "obstructed": "blocked",
    "impassable": "blocked"
  },
  "type": {
    "area": "location",
    "county": "location",
    "state": "location",
    "zone": "location",
    "province": "region",
    "region": "region",
    "country": "region",
    "territory": "region",
    "town": "settlement",
    "village": "settlement",
    "settlement": "settlement",
    "district": "district",
    "neighborhood": "district",
    "quarter": "district",
    "ward": "district",
    "street": "district",
    "avenue": "district",
    "structure": "exterior",
    "edifice": "exterior",
    "building": "exterior",
    "tower": "exterior",
    "house": "exterior",
    "home": "exterior",
    "residence": "exterior",
    "complex": "exterior",
    "facility": "exterior",
    "fort": "exterior",
    "castle": "exterior",
    "spaceship": "exterior",
    "starship": "exterior",
    "spacecraft": "exterior",
    "hull": "exterior",
    "hangar": "exterior",
    "interior": "interior",
    "inside": "interior",
    "deck": "interior",
    "level": "interior",
    "floor": "interior",
    "module": "interior",
    "outside": "exterior",
    "exterior": "exterior",
    "exterior space": "exterior",
    "courtyard": "exterior",
    "chamber": "room",
    "hall": "room",
    "bridge": "room",
    "engine room": "room",
    "reactor room": "room",
    "cockpit": "room",
    "control room": "room",
    "control center": "room",
    "cabin": "room",
    "quarters": "room",
    "suite": "room",
    "compartment": "room",
    "landmark": "feature",
    "spot": "feature",
    "forest": "region",
    "woods": "region",
    "jungle": "region",
    "grove": "region",
    "mountain": "region",
    "mountains": "region",
    "range": "region",
    "peak": "region",
    "valley": "region",
    "desert": "region",
    "swamp": "region",
    "marsh": "region",
    "marshland": "region",
    "bog": "region",
    "fen": "region",
    "sea": "region",
    "ocean": "region",
    "open sea": "region",
    "open ocean": "region",
    "coast": "region",
    "coastline": "region",
    "shore": "region",
    "island": "region",
    "archipelago": "region",
    "peninsula": "region",
    "plateau": "region",
    "hill": "region",
    "hills": "region",
    "plains": "region",
    "lake": "region",
    "bay": "region",
    "lagoon": "region",
    "fjord": "region",
    "river": "feature",
    "stream": "feature",
    "creek": "feature",
    "waterfall": "feature",
    "beach": "feature",
    "cliff": "feature",
    "canyon": "feature",
    "gorge": "feature",
    "ravine": "feature",
    "reef": "feature",
    "cave": "feature",
    "cavern": "feature",
    "grotto": "feature",
    "console": "feature",
    "terminal": "feature",
    "airlock": "feature",
    "hatch": "feature",
    "default": "feature"
  },
  "remove": [
    "removed",
    "deleted",
    "destroyed",
    "eliminated",
    "erased",
    "gone",
    "lost",
    "obliterated",
    "terminated",
    "discarded"
  ]
};

export default mapNodeSynonyms;
