import { MapNodeData, MapEdgeData } from '../types';

export const NODE_STATUS_SYNONYMS: Record<string, MapNodeData['status']> = {
  unknown: 'undiscovered',
  unexplored: 'undiscovered',
  found: 'discovered',
  revealed: 'discovered',
  rumoured: 'rumored',
  speculation: 'rumored',
  whispered: 'rumored',
  goal: 'quest_target',
  objective: 'quest_target'
};

export const NODE_TYPE_SYNONYMS: Record<string, NonNullable<MapNodeData['nodeType']>> = {
  area: 'location',
  zone: 'location',
  province: 'region',
  territory: 'region',
  town: 'settlement',
  village: 'settlement',
  settlement: 'settlement',
  structure: 'exterior',
  edifice: 'exterior',
  building: 'exterior',
  tower: 'exterior',
  house: 'exterior',
  fort: 'exterior',
  castle: 'exterior',
  interior: 'interior',
  inside: 'interior',
  outside: 'exterior',
  courtyard: 'exterior',
  chamber: 'room',
  hall: 'room',
  landmark: 'feature',
  spot: 'feature',
  forest: 'region',
  woods: 'region',
  jungle: 'region',
  grove: 'region',
  mountain: 'region',
  mountains: 'region',
  range: 'region',
  peak: 'region',
  valley: 'region',
  desert: 'region',
  swamp: 'region',
  marsh: 'region',
  marshland: 'region',
  bog: 'region',
  fen: 'region',
  sea: 'region',
  ocean: 'region',
  'open sea': 'region',
  'open ocean': 'region',
  coast: 'region',
  coastline: 'region',
  shore: 'region',
  island: 'region',
  archipelago: 'region',
  peninsula: 'region',
  plateau: 'region',
  hill: 'region',
  hills: 'region',
  plains: 'region',
  lake: 'region',
  bay: 'region',
  lagoon: 'region',
  fjord: 'region',
  river: 'feature',
  stream: 'feature',
  creek: 'feature',
  waterfall: 'feature',
  beach: 'feature',
  cliff: 'feature',
  canyon: 'feature',
  gorge: 'feature',
  ravine: 'feature',
  reef: 'feature',
  cave: 'feature',
  cavern: 'feature',
  grotto: 'feature'
};

export const EDGE_TYPE_SYNONYMS: Record<string, MapEdgeData['type']> = {
  trail: 'path',
  track: 'path',
  walkway: 'path',
  footpath: 'path',
  street: 'road',
  roadway: 'road',
  highway: 'road',
  lane: 'road',
  avenue: 'road',
  boulevard: 'road',
  seaway: 'sea route',
  'sea path': 'sea route',
  'ocean route': 'sea route',
  portal: 'teleporter',
  warp: 'teleporter',
  gate: 'door',
  gateway: 'door',
  'secret passageway': 'secret_passage',
  hidden_passage: 'secret_passage',
  tunnel: 'secret_passage',
  ford: 'river_crossing',
  ferry: 'river_crossing',
  bridge: 'temporary_bridge',
  'makeshift_bridge': 'temporary_bridge',
  'temporary crossing': 'temporary_bridge',
  grapple: 'boarding_hook',
  'grappling_hook': 'boarding_hook'
};

export const EDGE_STATUS_SYNONYMS: Record<string, MapEdgeData['status']> = {
  opened: 'open',
  usable: 'accessible',
  available: 'accessible',
  shut: 'closed',
  sealed: 'locked',
  barred: 'locked',
  obstructed: 'blocked',
  barricaded: 'blocked',
  concealed: 'hidden',
  secret: 'hidden',
  rumoured: 'rumored',
  legendary: 'rumored',
  'one way': 'one_way',
  'one-way': 'one_way',
  single_direction: 'one_way',
  fallen: 'collapsed',
  deactivated: 'inactive'
};
